name: Manual Workflow

on:
  workflow_dispatch:  # This makes the workflow run only when triggered manually

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run manual task
        run: echo "This workflow runs only when triggered manually!"
